import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/app/components/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Adsvate",
  description: "Generated by Huddin",
};

export default async function RootLayout({children}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="id">
      <body className={`${montserrat.variable} ${poppins.variable} ${poppins.className} antialiased`}>
        <Navbar />
         {children}
      </body>
    </html>
  );
}
