import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Adsvate",
  description: "Generated by Huddin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${poppins.variable} ${poppins.className} antialiased`}>
        <div className="relative overflow-hidden">
          <div className="w-[700px] h-[700px] shadow-[4px_4px_4px_5px_#000000] opacity-5 absolute -top-[35%] -left-[27%] rounded-full"></div>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
