import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/app/components/Navbar";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import Starfield from "@/app/components/Home/Starfield";

type Props = {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
};


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Adsvate",
  description: "Generated by Huddin",
  icons: {
    icon: '/favicon.ico',
  },
};

export default async function RootLayout({children, params}: Props) {

  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html>
      <body className={`${montserrat.variable} ${poppins.variable} ${poppins.className} antialiased`}>
        {/* <Starfield /> Bahaya ini ngelag! */}
        <NextIntlClientProvider>
          <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
